# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generatr.ui'
#
# Created: Thu Apr 21 17:05:32 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Generatr(object):
    def setupUi(self, Generatr):
        Generatr.setObjectName(_fromUtf8("Generatr"))
        Generatr.resize(642, 787)
        self.tabWidget = QtGui.QTabWidget(Generatr)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 781))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 571, 81))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.check_binary = QtGui.QCheckBox(self.groupBox)
        self.check_binary.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_binary.setObjectName(_fromUtf8("check_binary"))
        self.check_even = QtGui.QCheckBox(self.groupBox)
        self.check_even.setGeometry(QtCore.QRect(120, 30, 97, 22))
        self.check_even.setObjectName(_fromUtf8("check_even"))
        self.check_tri = QtGui.QCheckBox(self.groupBox)
        self.check_tri.setGeometry(QtCore.QRect(240, 30, 97, 22))
        self.check_tri.setObjectName(_fromUtf8("check_tri"))
        self.check_henon = QtGui.QCheckBox(self.groupBox)
        self.check_henon.setGeometry(QtCore.QRect(10, 60, 97, 22))
        self.check_henon.setObjectName(_fromUtf8("check_henon"))
        self.check_10dbq1 = QtGui.QCheckBox(self.groupBox)
        self.check_10dbq1.setGeometry(QtCore.QRect(120, 60, 111, 22))
        self.check_10dbq1.setObjectName(_fromUtf8("check_10dbq1"))
        self.check_ternary = QtGui.QCheckBox(self.groupBox)
        self.check_ternary.setGeometry(QtCore.QRect(360, 30, 97, 22))
        self.check_ternary.setObjectName(_fromUtf8("check_ternary"))
        self.check_10dbq2 = QtGui.QCheckBox(self.groupBox)
        self.check_10dbq2.setGeometry(QtCore.QRect(240, 60, 111, 22))
        self.check_10dbq2.setObjectName(_fromUtf8("check_10dbq2"))
        self.check_15dbq1 = QtGui.QCheckBox(self.groupBox)
        self.check_15dbq1.setGeometry(QtCore.QRect(360, 60, 111, 22))
        self.check_15dbq1.setObjectName(_fromUtf8("check_15dbq1"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 120, 571, 81))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.check_dmarkov = QtGui.QCheckBox(self.groupBox_2)
        self.check_dmarkov.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_dmarkov.setObjectName(_fromUtf8("check_dmarkov"))
        self.line_d_ini = QtGui.QLineEdit(self.groupBox_2)
        self.line_d_ini.setGeometry(QtCore.QRect(110, 60, 41, 20))
        self.line_d_ini.setObjectName(_fromUtf8("line_d_ini"))
        self.line_d_fin = QtGui.QLineEdit(self.groupBox_2)
        self.line_d_fin.setGeometry(QtCore.QRect(210, 60, 41, 21))
        self.line_d_fin.setObjectName(_fromUtf8("line_d_fin"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(40, 60, 66, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 66, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 220, 571, 151))
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.check_mk1 = QtGui.QCheckBox(self.groupBox_3)
        self.check_mk1.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_mk1.setObjectName(_fromUtf8("check_mk1"))
        self.check_mk1_old = QtGui.QCheckBox(self.groupBox_3)
        self.check_mk1_old.setGeometry(QtCore.QRect(10, 60, 111, 22))
        self.check_mk1_old.setObjectName(_fromUtf8("check_mk1_old"))
        self.check_mk1_new = QtGui.QCheckBox(self.groupBox_3)
        self.check_mk1_new.setGeometry(QtCore.QRect(130, 60, 111, 22))
        self.check_mk1_new.setObjectName(_fromUtf8("check_mk1_new"))
        self.check_mk1_dmark = QtGui.QCheckBox(self.groupBox_3)
        self.check_mk1_dmark.setGeometry(QtCore.QRect(260, 60, 171, 22))
        self.check_mk1_dmark.setObjectName(_fromUtf8("check_mk1_dmark"))
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(40, 120, 66, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.check_multi_moore = QtGui.QCheckBox(self.groupBox_3)
        self.check_multi_moore.setGeometry(QtCore.QRect(10, 90, 151, 22))
        self.check_multi_moore.setObjectName(_fromUtf8("check_multi_moore"))
        self.line_moore_fin = QtGui.QLineEdit(self.groupBox_3)
        self.line_moore_fin.setGeometry(QtCore.QRect(210, 120, 41, 21))
        self.line_moore_fin.setObjectName(_fromUtf8("line_moore_fin"))
        self.line_moore_ini = QtGui.QLineEdit(self.groupBox_3)
        self.line_moore_ini.setGeometry(QtCore.QRect(110, 120, 41, 20))
        self.line_moore_ini.setObjectName(_fromUtf8("line_moore_ini"))
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(160, 120, 66, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 370, 571, 81))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.check_mk2 = QtGui.QCheckBox(self.groupBox_4)
        self.check_mk2.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_mk2.setObjectName(_fromUtf8("check_mk2"))
        self.check_mk2_old = QtGui.QCheckBox(self.groupBox_4)
        self.check_mk2_old.setGeometry(QtCore.QRect(10, 60, 111, 22))
        self.check_mk2_old.setObjectName(_fromUtf8("check_mk2_old"))
        self.check_mk2_new = QtGui.QCheckBox(self.groupBox_4)
        self.check_mk2_new.setGeometry(QtCore.QRect(130, 60, 111, 22))
        self.check_mk2_new.setObjectName(_fromUtf8("check_mk2_new"))
        self.check_mk2_dmark = QtGui.QCheckBox(self.groupBox_4)
        self.check_mk2_dmark.setGeometry(QtCore.QRect(260, 60, 171, 22))
        self.check_mk2_dmark.setObjectName(_fromUtf8("check_mk2_dmark"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 470, 571, 81))
        self.groupBox_5.setAutoFillBackground(True)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.check_multL = QtGui.QCheckBox(self.groupBox_5)
        self.check_multL.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_multL.setObjectName(_fromUtf8("check_multL"))
        self.line_L_ini = QtGui.QLineEdit(self.groupBox_5)
        self.line_L_ini.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_L_ini.setObjectName(_fromUtf8("line_L_ini"))
        self.line_L_fin = QtGui.QLineEdit(self.groupBox_5)
        self.line_L_fin.setGeometry(QtCore.QRect(220, 60, 41, 21))
        self.line_L_fin.setObjectName(_fromUtf8("line_L_fin"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBox_5)
        self.label_4.setGeometry(QtCore.QRect(170, 60, 66, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(320, 30, 66, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_single_L = QtGui.QLineEdit(self.groupBox_5)
        self.line_single_L.setGeometry(QtCore.QRect(390, 30, 41, 20))
        self.line_single_L.setObjectName(_fromUtf8("line_single_L"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 580, 571, 81))
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.check_multi_alpha = QtGui.QCheckBox(self.groupBox_6)
        self.check_multi_alpha.setGeometry(QtCore.QRect(10, 30, 131, 22))
        self.check_multi_alpha.setObjectName(_fromUtf8("check_multi_alpha"))
        self.line_alpha_ini = QtGui.QLineEdit(self.groupBox_6)
        self.line_alpha_ini.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_alpha_ini.setObjectName(_fromUtf8("line_alpha_ini"))
        self.line_alpha_fin = QtGui.QLineEdit(self.groupBox_6)
        self.line_alpha_fin.setGeometry(QtCore.QRect(240, 60, 41, 21))
        self.line_alpha_fin.setObjectName(_fromUtf8("line_alpha_fin"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(25, 60, 91, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(170, 60, 66, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(320, 30, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_single_alpha = QtGui.QLineEdit(self.groupBox_6)
        self.line_single_alpha.setGeometry(QtCore.QRect(420, 30, 41, 20))
        self.line_single_alpha.setObjectName(_fromUtf8("line_single_alpha"))
        self.saveconf = QtGui.QPushButton(self.tab)
        self.saveconf.setGeometry(QtCore.QRect(260, 710, 98, 27))
        self.saveconf.setObjectName(_fromUtf8("saveconf"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gengraph = QtGui.QPushButton(self.tab_5)
        self.gengraph.setGeometry(QtCore.QRect(250, 300, 121, 27))
        self.gengraph.setObjectName(_fromUtf8("gengraph"))
        self.bar_gengraph = QtGui.QProgressBar(self.tab_5)
        self.bar_gengraph.setGeometry(QtCore.QRect(30, 350, 571, 23))
        self.bar_gengraph.setProperty("value", 0)
        self.bar_gengraph.setObjectName(_fromUtf8("bar_gengraph"))
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.genseq = QtGui.QPushButton(self.tab_2)
        self.genseq.setGeometry(QtCore.QRect(240, 290, 161, 27))
        self.genseq.setObjectName(_fromUtf8("genseq"))
        self.check_original = QtGui.QCheckBox(self.tab_2)
        self.check_original.setEnabled(True)
        self.check_original.setGeometry(QtCore.QRect(230, 80, 191, 22))
        self.check_original.setObjectName(_fromUtf8("check_original"))
        self.label_20 = QtGui.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(240, 180, 66, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.line_length = QtGui.QLineEdit(self.tab_2)
        self.line_length.setGeometry(QtCore.QRect(310, 180, 91, 20))
        self.line_length.setObjectName(_fromUtf8("line_length"))
        self.bar_genseq = QtGui.QProgressBar(self.tab_2)
        self.bar_genseq.setGeometry(QtCore.QRect(30, 380, 571, 23))
        self.bar_genseq.setProperty("value", 0)
        self.bar_genseq.setObjectName(_fromUtf8("bar_genseq"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_13 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 20, 571, 81))
        self.groupBox_13.setAutoFillBackground(True)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.check_entropy = QtGui.QCheckBox(self.groupBox_13)
        self.check_entropy.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_entropy.setObjectName(_fromUtf8("check_entropy"))
        self.line_entropy = QtGui.QLineEdit(self.groupBox_13)
        self.line_entropy.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_entropy.setObjectName(_fromUtf8("line_entropy"))
        self.label_21 = QtGui.QLabel(self.groupBox_13)
        self.label_21.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.groupBox_14 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_14.setGeometry(QtCore.QRect(20, 150, 571, 81))
        self.groupBox_14.setAutoFillBackground(True)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.check_autocorr = QtGui.QCheckBox(self.groupBox_14)
        self.check_autocorr.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_autocorr.setObjectName(_fromUtf8("check_autocorr"))
        self.line_autocorr = QtGui.QLineEdit(self.groupBox_14)
        self.line_autocorr.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_autocorr.setObjectName(_fromUtf8("line_autocorr"))
        self.label_22 = QtGui.QLabel(self.groupBox_14)
        self.label_22.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.groupBox_15 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 250, 571, 81))
        self.groupBox_15.setAutoFillBackground(True)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.check_kld = QtGui.QCheckBox(self.groupBox_15)
        self.check_kld.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_kld.setObjectName(_fromUtf8("check_kld"))
        self.line_kld = QtGui.QLineEdit(self.groupBox_15)
        self.line_kld.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_kld.setObjectName(_fromUtf8("line_kld"))
        self.label_23 = QtGui.QLabel(self.groupBox_15)
        self.label_23.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.analyze = QtGui.QPushButton(self.tab_3)
        self.analyze.setGeometry(QtCore.QRect(260, 560, 121, 27))
        self.analyze.setObjectName(_fromUtf8("analyze"))
        self.bar_an_seq = QtGui.QProgressBar(self.tab_3)
        self.bar_an_seq.setGeometry(QtCore.QRect(40, 620, 571, 23))
        self.bar_an_seq.setProperty("value", 0)
        self.bar_an_seq.setObjectName(_fromUtf8("bar_an_seq"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_16.setGeometry(QtCore.QRect(20, 350, 571, 81))
        self.groupBox_16.setAutoFillBackground(True)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.check_l1metric = QtGui.QCheckBox(self.groupBox_16)
        self.check_l1metric.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_l1metric.setObjectName(_fromUtf8("check_l1metric"))
        self.line_l1metric = QtGui.QLineEdit(self.groupBox_16)
        self.line_l1metric.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_l1metric.setObjectName(_fromUtf8("line_l1metric"))
        self.label_24 = QtGui.QLabel(self.groupBox_16)
        self.label_24.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.groupBox_17 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_17.setGeometry(QtCore.QRect(20, 450, 571, 81))
        self.groupBox_17.setAutoFillBackground(True)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.check_kldmetric = QtGui.QCheckBox(self.groupBox_17)
        self.check_kldmetric.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.check_kldmetric.setObjectName(_fromUtf8("check_kldmetric"))
        self.line_kldmetric = QtGui.QLineEdit(self.groupBox_17)
        self.line_kldmetric.setGeometry(QtCore.QRect(120, 60, 41, 20))
        self.line_kldmetric.setObjectName(_fromUtf8("line_kldmetric"))
        self.label_25 = QtGui.QLabel(self.groupBox_17)
        self.label_25.setGeometry(QtCore.QRect(50, 60, 66, 16))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.plot = QtGui.QPushButton(self.tab_4)
        self.plot.setGeometry(QtCore.QRect(260, 610, 121, 27))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.groupBox_25 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_25.setGeometry(QtCore.QRect(20, 220, 571, 81))
        self.groupBox_25.setAutoFillBackground(True)
        self.groupBox_25.setObjectName(_fromUtf8("groupBox_25"))
        self.plot_kld = QtGui.QCheckBox(self.groupBox_25)
        self.plot_kld.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.plot_kld.setObjectName(_fromUtf8("plot_kld"))
        self.plot_kld_bynostates = QtGui.QCheckBox(self.groupBox_25)
        self.plot_kld_bynostates.setGeometry(QtCore.QRect(10, 50, 171, 22))
        self.plot_kld_bynostates.setObjectName(_fromUtf8("plot_kld_bynostates"))
        self.groupBox_26 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_26.setGeometry(QtCore.QRect(20, 120, 571, 81))
        self.groupBox_26.setAutoFillBackground(True)
        self.groupBox_26.setObjectName(_fromUtf8("groupBox_26"))
        self.plot_autocorr = QtGui.QCheckBox(self.groupBox_26)
        self.plot_autocorr.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.plot_autocorr.setObjectName(_fromUtf8("plot_autocorr"))
        self.groupBox_27 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_27.setGeometry(QtCore.QRect(20, 20, 571, 81))
        self.groupBox_27.setAutoFillBackground(True)
        self.groupBox_27.setObjectName(_fromUtf8("groupBox_27"))
        self.plot_entropy = QtGui.QCheckBox(self.groupBox_27)
        self.plot_entropy.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.plot_entropy.setObjectName(_fromUtf8("plot_entropy"))
        self.plot_entropy_bynostates = QtGui.QCheckBox(self.groupBox_27)
        self.plot_entropy_bynostates.setGeometry(QtCore.QRect(10, 50, 171, 22))
        self.plot_entropy_bynostates.setObjectName(_fromUtf8("plot_entropy_bynostates"))
        self.groupBox_28 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_28.setGeometry(QtCore.QRect(20, 320, 571, 81))
        self.groupBox_28.setAutoFillBackground(True)
        self.groupBox_28.setObjectName(_fromUtf8("groupBox_28"))
        self.plot_l1metric = QtGui.QCheckBox(self.groupBox_28)
        self.plot_l1metric.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.plot_l1metric.setObjectName(_fromUtf8("plot_l1metric"))
        self.plot_l1metric_bynostate = QtGui.QCheckBox(self.groupBox_28)
        self.plot_l1metric_bynostate.setGeometry(QtCore.QRect(10, 50, 171, 22))
        self.plot_l1metric_bynostate.setObjectName(_fromUtf8("plot_l1metric_bynostate"))
        self.groupBox_29 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_29.setGeometry(QtCore.QRect(20, 420, 571, 81))
        self.groupBox_29.setAutoFillBackground(True)
        self.groupBox_29.setObjectName(_fromUtf8("groupBox_29"))
        self.plot_kldmetric = QtGui.QCheckBox(self.groupBox_29)
        self.plot_kldmetric.setGeometry(QtCore.QRect(10, 30, 97, 22))
        self.plot_kldmetric.setObjectName(_fromUtf8("plot_kldmetric"))
        self.plot_kldmetric_bynostates = QtGui.QCheckBox(self.groupBox_29)
        self.plot_kldmetric_bynostates.setGeometry(QtCore.QRect(10, 50, 171, 22))
        self.plot_kldmetric_bynostates.setObjectName(_fromUtf8("plot_kldmetric_bynostates"))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Generatr)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Generatr)

    def retranslateUi(self, Generatr):
        Generatr.setWindowTitle(_translate("Generatr", "Form", None))
        self.groupBox.setTitle(_translate("Generatr", "Type", None))
        self.check_binary.setText(_translate("Generatr", "Binary", None))
        self.check_even.setText(_translate("Generatr", "Even", None))
        self.check_tri.setText(_translate("Generatr", "Tri", None))
        self.check_henon.setText(_translate("Generatr", "Henon", None))
        self.check_10dbq1.setText(_translate("Generatr", "10 dB q =1", None))
        self.check_ternary.setText(_translate("Generatr", "Ternary", None))
        self.check_10dbq2.setText(_translate("Generatr", "10 dB q = 2", None))
        self.check_15dbq1.setText(_translate("Generatr", "15 dB q = 1", None))
        self.groupBox_2.setTitle(_translate("Generatr", "D-Markov", None))
        self.check_dmarkov.setText(_translate("Generatr", "Enable", None))
        self.label.setText(_translate("Generatr", "From D =", None))
        self.label_2.setText(_translate("Generatr", "to D=", None))
        self.groupBox_3.setTitle(_translate("Generatr", "Mk1", None))
        self.check_mk1.setText(_translate("Generatr", "Enable", None))
        self.check_mk1_old.setText(_translate("Generatr", "Expansion 1", None))
        self.check_mk1_new.setText(_translate("Generatr", "Expansion 2", None))
        self.check_mk1_dmark.setText(_translate("Generatr", "D-Markov Expansion", None))
        self.label_6.setText(_translate("Generatr", "From I =", None))
        self.check_multi_moore.setText(_translate("Generatr", "Moore Iterations", None))
        self.label_7.setText(_translate("Generatr", "to I =", None))
        self.groupBox_4.setTitle(_translate("Generatr", "Mk2", None))
        self.check_mk2.setText(_translate("Generatr", "Enable", None))
        self.check_mk2_old.setText(_translate("Generatr", "Expansion 1", None))
        self.check_mk2_new.setText(_translate("Generatr", "Expansion 2", None))
        self.check_mk2_dmark.setText(_translate("Generatr", "D-Markov Expansion", None))
        self.groupBox_5.setTitle(_translate("Generatr", "L", None))
        self.check_multL.setText(_translate("Generatr", "Multiple L", None))
        self.label_3.setText(_translate("Generatr", "From L =", None))
        self.label_4.setText(_translate("Generatr", "to L=", None))
        self.label_5.setText(_translate("Generatr", "Single L =", None))
        self.groupBox_6.setTitle(_translate("Generatr", "Alpha", None))
        self.check_multi_alpha.setText(_translate("Generatr", "Multiple Alpha", None))
        self.label_9.setText(_translate("Generatr", "From alpha =", None))
        self.label_10.setText(_translate("Generatr", "to alpha=", None))
        self.label_11.setText(_translate("Generatr", "Single alpha =", None))
        self.saveconf.setText(_translate("Generatr", "Save Config", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Generatr", "General Configurations", None))
        self.gengraph.setText(_translate("Generatr", "Generate Graphs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Generatr", "Generate Graphs", None))
        self.genseq.setText(_translate("Generatr", "Generate Sequences", None))
        self.check_original.setText(_translate("Generatr", "Generate From Original", None))
        self.label_20.setText(_translate("Generatr", "Length:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Generatr", "Generate Sequences", None))
        self.groupBox_13.setTitle(_translate("Generatr", "Conditional Entropies", None))
        self.check_entropy.setText(_translate("Generatr", "Enable", None))
        self.label_21.setText(_translate("Generatr", "Up to:", None))
        self.groupBox_14.setTitle(_translate("Generatr", "Autocorrelations", None))
        self.check_autocorr.setText(_translate("Generatr", "Enable", None))
        self.label_22.setText(_translate("Generatr", "Up to:", None))
        self.groupBox_15.setTitle(_translate("Generatr", "Kullback-Leibler Divergence", None))
        self.check_kld.setText(_translate("Generatr", "Enable", None))
        self.label_23.setText(_translate("Generatr", "Length:", None))
        self.analyze.setText(_translate("Generatr", "Analyze", None))
        self.groupBox_16.setTitle(_translate("Generatr", "L1-Metric", None))
        self.check_l1metric.setText(_translate("Generatr", "Enable", None))
        self.label_24.setText(_translate("Generatr", "Length:", None))
        self.groupBox_17.setTitle(_translate("Generatr", "KLD-Metric", None))
        self.check_kldmetric.setText(_translate("Generatr", "Enable", None))
        self.label_25.setText(_translate("Generatr", "Length:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Generatr", "Analyze Sequences", None))
        self.plot.setText(_translate("Generatr", "Plot", None))
        self.groupBox_25.setTitle(_translate("Generatr", "Kullback-Leibler Divergence", None))
        self.plot_kld.setText(_translate("Generatr", "Enable", None))
        self.plot_kld_bynostates.setText(_translate("Generatr", "By Number of States", None))
        self.groupBox_26.setTitle(_translate("Generatr", "Autocorrelations", None))
        self.plot_autocorr.setText(_translate("Generatr", "Enable", None))
        self.groupBox_27.setTitle(_translate("Generatr", "Conditional Entropies", None))
        self.plot_entropy.setText(_translate("Generatr", "Enable", None))
        self.plot_entropy_bynostates.setText(_translate("Generatr", "By Number of States", None))
        self.groupBox_28.setTitle(_translate("Generatr", "L1-Metric", None))
        self.plot_l1metric.setText(_translate("Generatr", "Enable", None))
        self.plot_l1metric_bynostate.setText(_translate("Generatr", "By Number of States", None))
        self.groupBox_29.setTitle(_translate("Generatr", "KLD-Metric", None))
        self.plot_kldmetric.setText(_translate("Generatr", "Enable", None))
        self.plot_kldmetric_bynostates.setText(_translate("Generatr", "By Number of States", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Generatr", "Plots", None))

